# Generated by Django 3.2.12 on 2022-04-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_movieinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set movie as returned'),)},
        ),
    ]
